//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFIDWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFIDDevice
    {
        public int RFIDDeviceId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceKey { get; set; }
        public System.DateTime DeviceAuthorizedDate { get; set; }
        public string DeviceAuthorizedBy { get; set; }
        public string DeviceLocation { get; set; }
        public string DeviceDepartment { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
